### ISSUE TITLE
Duration is not displayed correctly

### ISSUE THREAD

**Issue by unregd** [stuerp/foo_sid#2]
Hi,

Clean install of FB2K 2.0 + foo_sid 1.93.0.0
After loading the songlengths.md5 from HVSC the .sid files are played with the correct duration, but FB2K still shows the "default length" 3:00 for every track.

**Comment by stuerp** [comment]
Confirmed. It's a regression due to refactoring. I'll try to fix it ASAP.

**Comment by unregd** [comment]
Thank you for looking into it!

I used the browser to select it, didn't type in anything, foo_sid says the DB is lodaded and FB2K plays them correctly so it has to be, except it doesn't show the correct length.

... and as it looks like I've found some .sid files from the HVSC that all act this way by sheer luck :)

Yie_Ar_Kung_Fu.sid
Yie_Ar_Kung_Fu_II.sid
both from Martin Galway

[https://i.imgur.com/DtZlwoF.png](url)

**Comment by stuerp** [comment]
If you first added the files to a playlist and only later configured the database file foobar2000 will keep displaying the initial tag values.
Select the files and use "Tagging/Reload info from file(s)" to rescan the files.

**Comment by unregd** [comment]
After these experiences and helpful suggestions I've found/learned/understood FB2K now (as of 2.0) has a metadb.sqlite "cache" about the files that were added to a playlist and it doesn't update it unless the files change in some way. Removing then re-adding them to a playlist is not enough. FB2K loads all the information (duration) about the files from this db, as being faster than actually opening and analyzing them every time it starts or they are being added.
Now, above this, the only way to manually force a refresh of this cached data is in a sub-sub menu that is not even enabled by default. *sigh*
A warning in the component description with how to manually refresh the duration would be helpful I think.

**Comment by stuerp** [comment]
I realize it's not intuitive at first but it only poses a problem for 'old' and 'non-native' music formats: most modern audio formats carry all meta information on-board and get scanned correctly when first added. I'll add some text to the README for new users.
I assume foobar2000 was never intended for the casual user and requires some effort to harness its power.
