### ISSUE TITLE
.sid playback broken when Songlengths.md5 is on a UNC path

### ISSUE THREAD

**Issue by rlnilsen** [stuerp/foo_sid#6]
This DB path does not work:
`\\fileserver\share\Audio\_Synthesized\SID\DOCUMENTS\Songlengths.md5` 

But mapping the share to a drive letter works:
`Z:\Audio\_Synthesized\SID\DOCUMENTS\Songlengths.md5`

![Screenshot 2024-07-14 024052](https://github.com/user-attachments/assets/1986c078-b22b-4174-b06d-1270fbc1cdc9)

Attempting to play item in playlist:
![Screenshot 2024-07-14 024429](https://github.com/user-attachments/assets/ca8d8d79-41f6-4e85-a0c9-b9919225a1c4)

Opening .sid file from File Explorer:
![Screenshot 2024-07-14 024116](https://github.com/user-attachments/assets/7c880803-610b-401b-9d7b-8aaa79737c96)

Windows 10 Home 22H2 x64
fb2k 2.1.5 x86
foo_sid 1.98.00

**Comment by stuerp** [comment]
I'm unable to reproduce this. The SID's and MD5 loads just fine from an UNC path in my setup.

**Comment by rlnilsen** [comment]
I should add that this was with OpenMediaVault v4.1.36-1 as the SMB file server, which somehow can result in Windows giving two different string values for the same path. PR #7 explains the details.
