### ISSUE TITLE
Issue with builds done on VS 17.10 and newer

### ISSUE THREAD

**Issue by rlnilsen** [stuerp/foo_sid#8]
Just a heads up, issue described [here](https://developercommunity.visualstudio.com/t/Visual-Studio-17100-Update-leads-to-Pr/10669759?sort=newest). Debug build was fine for me, but release builds would crash FB2K (x86). Installing the newest vcredist did not help, but defining _DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR did.

**Comment by stuerp** [comment]
Thx for the heads up. I'll look at it later; got too much on my plate now with the other components.

**Comment by stuerp** [comment]
Added the definition and upgraded the projects to C++ 20.
